### ISSUE TITLE
Cannot place the initial window

### ISSUE THREAD

**Issue by rp-first** [rp-first/FrcFieldHololens1#1]
When the application starts the initial window follows my gaze as I move my head around, an air-tap does not cause the window to lock to a fixed location.

**Comment by rp-first** [comment]
An air-tap should cause the window to lock to it's current location. If that is
not working, you can try saying "lock window" to lock the window in place. There
is also an "unpin window" verbal command that is the opposite of "lock window".

The air-tap may not be working because the committed project was 
built with a different version of Unity than what you are using.  What is in 
the repository was originally built with Unity 5.4.03f (that may change in the 
future). If you are using a different version, you may need to replace the 
Hololens Input Module to update it's GUID. Just remove the one in the project, 
then add it back in. Here's a little more detail.

- In the Hierarchy pane, click on the EventSystem item
- In the Inspector pane, find the "Holo Lens Input Module" section, click on the gear icon and select "Remove Component" 
- In the Inspector pane, click on the "Add Component" button
  - At the top of the compnenet list there is a search box, type "Input" into it
  - Click on the "HoloLens Input Module" item in the list
- Rebuild and deploy the application  

This process has worked for at least one person.

**Comment by fporter2** [comment]
This is fixed with the recent changes for supporting 5.5.x. The official version should not have any GUID changes for their modules.

Also tagged the last revision for 5.4.x if anyone needs to use that commit.
